services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - 8082:8080
    networks:
      - test-network
    volumes:
      - ./:/tmp
    environment:
      - SWAGGER_FILE=/tmp/openapi.yml
  rabbitmq:
    image: rabbitmq:3.7.25-management-alpine
    container_name: rabbitmq
    ports: 
     - 5672:5672
     - 15672:15672
    networks:
     - test-network

networks:
  test-network:
    driver: bridge