services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - 8082:8080
    networks:
      - test-network
    volumes:
      - ./:/tmp
    environment:
      - SWAGGER_FILE=/tmp/openapi.yml
networks:
  test-network:
    driver: bridge